# fly.toml app configuration file generated for phonebook-fullstack-course on 2024-12-02T00:24:42+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'phonebook-fullstack-course'
primary_region = 'arn'

[build]

[env]
  PORT = "3000" # add this

[http_service]
  internal_port = 3000 
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
