### get All
GET https://phonebook-fullstack-course.fly.dev/api/persons

### get a person with id
GET https://phonebook-fullstack-course.fly.dev/api/persons/1

### get a person with id (Not found)
GET https://phonebook-fullstack-course.fly.dev/api/persons/100

### get info
GET https://phonebook-fullstack-course.fly.dev/info

### delete with id
DELETE https://phonebook-fullstack-course.fly.dev/api/persons/1

### post
POST https://phonebook-fullstack-course.fly.dev/api/persons/
content-type: application/json

{
    "name": "dinosaur",
    "number": "12345"  
}

### post but name property is missing
POST https://phonebook-fullstack-course.fly.dev/api/persons/
content-type: application/json

{
    "number": "12345"  
}

### post but name is empty
POST https://phonebook-fullstack-course.fly.dev/api/persons/
content-type: application/json

{
    "name": "",
    "number": "12345"  
}

### post but name is not uniqe
POST https://phonebook-fullstack-course.fly.dev/api/persons/
content-type: application/json

{
    "name": "dinosaur",
    "number": "12345"  
}